# Don't include the <base> tag, to prevent variety of breakage in eg a local
# dev env
# baseURL = "http://morrolan.ch/"
languageCode = "en-us"
title = ""
theme = "coder"
defaultcontentlanguage = "en"

paginate = 20
# Don't use absolute URLs for locally-hosted files (eg stylesheets)
canonifyurls = false

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Morrolan"

    hidecredits = true
    hidecopyright = true

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/lavode/"
